### PR TITLE
client: replace faq with doc

### PR DESCRIPTION
**Pull request by philepsybo**

### CODE REVIEW

**Comment by PromyLOPh** [comment]
I would rename the files *.txt → *.md, but otherwise LGTM.

**Comment by philepsybo** [comment]
> I would rename the files *.txt → *.md, but otherwise LGTM.

I would have liked to do so but this is unfortunately not supported by the loader so far.
What we could do is to rename them to `[...].md.txt` to communicate at least some additional info about the file contents.

**Comment by PromyLOPh** [comment]
That’s pretty simple, I pushed the rename and added a loader mapping for .md files.

**Comment by PromyLOPh** [comment]
Merged as 47f968e97fb3b1ed65ffc3f1e6ac9fb9a67835f6

**Pull request closed without merging**
